version: 2.1
jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

    steps:
      - checkout
      - run: ls
      - run: dotnet build TestSwitchApi/TestSwitchApi/TestSwitchApi.csproj
      - run: dotnet build TestSwitchApi/TestSwitchApi.Tests/TestSwitchApi.Tests.csproj
      - run: dotnet test TestSwitchApi/TestSwitchApi.Tests/TestSwitchApi.Tests.csproj

workflows:
  build-and-test:
    jobs:
      - build-and-test